### Create hotel
POST http://localhost:7007/api/v1/hotel
Content-Type: application/json

{
  "hotelName": "Marienlyst",
  "hotelAddress": "banegårdsvej 14",
  "rooms": [
    {"number": "67", "price": 120.0},
    {"number": "14", "price": 150.0}
  ]
}


### GET alle hotels
GET http://localhost:7007/api/v1/hotel/


### GET hotel by id
GET http://localhost:7007/api/v1/hotel/1