###
POST http://localhost:7007/api/v1/auth/login

{
    "username": "user1",
    "password": "pass123"
}

###
GET http://localhost:7007/api/v1/protected/user_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIkFsaXNzYSBBbmRyZWEgU3Rvcm1cIiIsInN1YiI6InVzZXIxIiwiZXhwIjoxNzU5NDI0MDQ4LCJyb2xlcyI6IlVzZXIiLCJ1c2VybmFtZSI6InVzZXIxIn0.s6KGIAZt0ifi7ligVeo-G99QOUn8HWyiMknb2j79MtU
